[pytest]
norecursedirs = scripts frontend backend/Dataset_Management_tool/mlruns backend/Dataset_Management_tool/storage backend/Dataset_Management_tool/runs
testpaths = backend/Dataset_Management_tool/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov=backend/Dataset_Management_tool/app --cov-report=term-missing
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
